#!/usr/bin/env python3
"""
Extract and validate a schedule swap proposal from a GitHub Issue body.

Reads the issue body from the ISSUE_BODY environment variable,
extracts the proposed schedule JSON, validates it, and writes it
to output/schedule.json for further processing by schedule_builder.py.
"""

import json
import os
import re
import sys

# Add project root to path so we can import schedule_builder
sys.path.insert(
    0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..")
)
from schedule_builder import load_sessions, validate_schedule, ROOMS, load_versions


SLOT_LABELS = {
    "slot_1": "Slot 1 (08:30)",
    "slot_2": "Slot 2 (09:30)",
    "slot_3": "Slot 3 (10:30)",
    "slot_4": "Slot 4 (11:30)",
    "slot_5": "Slot 5 (02:00)",
    "slot_6": "Slot 6 (03:00)",
    "slot_7": "Slot 7 (04:00)",
}


def extract_schedule(body):
    """Extract proposed schedule JSON from the issue body."""
    if "<!-- SCHEDULE_SWAP -->" not in body:
        print("No SCHEDULE_SWAP marker found in issue body", file=sys.stderr)
        sys.exit(1)

    # Look for JSON code fence after "Proposed Schedule" heading
    match = re.search(
        r"### Proposed Schedule\s*```json\s*(\{.*?\})\s*```",
        body,
        re.DOTALL,
    )
    if not match:
        # Fallback: any JSON code fence containing slot_1
        match = re.search(
            r'```json\s*(\{[^`]*"slot_1"[^`]*\})\s*```',
            body,
            re.DOTALL,
        )

    if not match:
        print("Could not find schedule JSON in issue body", file=sys.stderr)
        sys.exit(1)

    try:
        return json.loads(match.group(1))
    except json.JSONDecodeError as e:
        print(f"Invalid JSON in schedule: {e}", file=sys.stderr)
        sys.exit(1)


def extract_changes_section(body):
    """Extract the human-readable Changes section from the issue body."""
    match = re.search(
        r"### Changes\s*\n(.*?)(?=\n###|\n---|\Z)",
        body,
        re.DOTALL,
    )
    return match.group(1).strip() if match else ""


def build_diff_summary(old_schedule, new_schedule, session_map):
    """Build a detailed diff of what moved where."""
    lines = []
    for slot_key in sorted(new_schedule.keys()):
        old_ids = old_schedule.get(slot_key, [])
        new_ids = new_schedule.get(slot_key, [])
        for pos in range(8):
            old_sid = old_ids[pos] if pos < len(old_ids) else None
            new_sid = new_ids[pos] if pos < len(new_ids) else None
            if old_sid != new_sid:
                room = ROOMS[pos]
                old_s = session_map.get(str(old_sid), {})
                new_s = session_map.get(str(new_sid), {})
                lines.append(
                    f"| {SLOT_LABELS.get(slot_key, slot_key)} | {room['alias']} ({room['capacity']}) "
                    f"| ~~{old_s.get('title', '?')}~~ ({old_s.get('speakers', '?')}) "
                    f"| **{new_s.get('title', '?')}** ({new_s.get('speakers', '?')}) |"
                )
    return lines


def main():
    body = os.environ.get("ISSUE_BODY", "")
    issue_num = os.environ.get("ISSUE_NUMBER", "?")

    if not body:
        print("ISSUE_BODY environment variable is empty", file=sys.stderr)
        sys.exit(1)

    print(f"Processing schedule swap from issue #{issue_num}...")

    # Extract schedule
    schedule = extract_schedule(body)

    # Normalize IDs to strings
    schedule = {k: [str(sid) for sid in v] for k, v in schedule.items()}

    # Validate against session data
    sessions = load_sessions()
    session_map = {s["id"]: s for s in sessions}
    ok, errors = validate_schedule(schedule, sessions)

    if not ok:
        print("Validation failed:", file=sys.stderr)
        for err in errors:
            print(f"  - {err}", file=sys.stderr)
        sys.exit(1)

    print("Validation passed")

    # Get the current schedule for diff
    versions = load_versions()
    current_schedule = versions[-1]["schedule"] if versions else {}
    current_version = versions[-1]["version"] if versions else "?"

    # Build PR body
    changes_section = extract_changes_section(body)
    diff_lines = build_diff_summary(current_schedule, schedule, session_map)

    pr_body = f"## Schedule Swap Proposal\n\n"
    pr_body += f"Proposed by @${{ISSUE_AUTHOR}} in #${{ISSUE_NUMBER}}.\n\n"

    if changes_section:
        pr_body += f"### Swaps Requested\n\n{changes_section}\n\n"

    if diff_lines:
        pr_body += "### Room Changes\n\n"
        pr_body += "| Slot | Room | Was | Now |\n"
        pr_body += "|------|------|-----|-----|\n"
        pr_body += "\n".join(diff_lines) + "\n\n"

    pr_body += "### Validation\n\n"
    pr_body += "- All 56 sessions assigned\n"
    pr_body += "- No speaker conflicts\n"
    pr_body += f"- Based on v{current_version}\n\n"
    pr_body += "---\n*Auto-generated by the Schedule Swap workflow*\n"

    # Write to output/schedule.json
    os.makedirs("output", exist_ok=True)
    with open("output/schedule.json", "w") as f:
        json.dump(schedule, f, indent=2)

    # Write PR body for workflow to pick up
    with open("output/pr_body.md", "w") as f:
        f.write(pr_body)

    print("Schedule written to output/schedule.json")
    print("PR body written to output/pr_body.md")


if __name__ == "__main__":
    main()
